server:
  forward-headers-strategy: framework

spring:
  application:
    name: PhocaMatch

  datasource:
    url: jdbc:mysql://phocamatch-db.c1a2wgc0c2nt.ap-northeast-2.rds.amazonaws.com:3306/phocamatch?useSSL=true&serverTimezone=Asia/Seoul
    username: admin
    password : ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - email

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

app:
  jwt:
    issuer: phocamatch
    secret: ${JWT_SECRET}
    access-token-expiration-seconds: 3600
    signup-token-expiration-seconds: 600
    refresh-token-expiration-seconds: 1209600  #14일

  cookie:
    secure: true
    same-site: None

  frontend:
    login-success-url: https://www.phocamatch.shop/oauth/callback
    login-failure-url: https://www.phocamatch.shop/login
    # login-success-url-local: http://localhost:3000/oauth/callback
    # login-failure-url-local: http://localhost:3000/login


cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: phocamatch-images-504815484015-ap-northeast-2-an
      public-base-url: https://phocamatch-images-504815484015-ap-northeast-2-an.s3.ap-northeast-2.amazonaws.com
